# Generated by Django 3.0.6 on 2020-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=99, unique=True, verbose_name="Name route"
                    ),
                ),
                ("from_city", models.CharField(max_length=99, verbose_name="From")),
                ("to_city", models.CharField(max_length=99, verbose_name="From")),
                ("travel_times", models.IntegerField(verbose_name="Travels times")),
                (
                    "across_cities",
                    models.ManyToManyField(
                        blank=True, to="trains.Train", verbose_name="Across cities"
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routers",
                "ordering": ["name"],
            },
        ),
    ]
