# Generated by Django 3.0.6 on 2020-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cities", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=99, unique=True, verbose_name="City"),
        )
    ]
