# Generated by Django 3.0.6 on 2020-05-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0003_auto_20200527_1938"),
        ("cities", "0003_auto_20200531_1657"),
    ]

    operations = []
